### ISSUE TITLE
RN on android doesn't like long timeouts (AccessManager)

### ISSUE THREAD

**Issue by marneborn** [twilio/TwilioChatJsReactNative#1]
This gets the same warning that we get using the JS AccessManager on Android

```
YellowBox.js:76 Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 86400000ms)
```

**Comment by aleksandrsivanovs** [comment]
thank you for the report - will check possible workarounds.

**Comment by nhandh2013** [comment]
hi @aleksandrsivanovs,
I have the same problem with him. 
Could you give me some solution to fix that?

**Comment by aleksandrsivanovs** [comment]
we are working on new version which will drop the need for this fix (hopefully).
haven't got to the actual testing of that new version on RN yet, though

**Comment by TomMahle** [comment]
@aleksandrsivanovs any update on the status of this? Seeing the same issues on

    "react-native": "0.53.3",
    "twilio-chat": "^2.2.0",
    "twilio-common": "^0.1.7",

And I'm not seeing any potential workarounds that wouldn't hide warnings for this issue in my own code (which I'd like to preserve).

**Comment by aleksandrsivanovs** [comment]
Hi, the workaround will be quite easy - we will remove need of accessmagaer and move token lifecycle events (token expired, about to expire and etc.) to the chat lib itself (and signal it through backend and not through the built in timers).
This will be new version 3.0.0 (with some breaking changes in api, but not very big changes). Currently the version is in internal verification, the rc1 hopefully coming out next week. I will post update with when rc1 will come out.

Hope that this will work for you (assuming that you are able to change some of your code to accommodate the breaking changes).

P.S. sorry for taking so much time (the new version was in the works since end of March)

**Comment by aleksandrsivanovs** [comment]
so, we have released the version 3.0.0, which essentially drops the need for AccessManager and removing AccessManager removes most of timeout warnings.

However, there is still one 24h timeout inside the twilio-sync lib we are using together with twilio-chat - we can't get rid of it now.

**Comment by wkoutre** [comment]
@aleksandrsivanovs I see this React Native example was updated 2 weeks ago:

https://github.com/twilio/TwilioChatJsReactNative/blob/bfc30dfbcd40b029f675a394fcd0ffdecc79eb92/js/chat-client-helper.js

Couple comments:

1) README has not been updated for 4 months.
2) Example has some ES6 (`import`, `export`), but.. not `arrow functions`, `async/await`, destructuring. Would be better to make it all or nothing to really have something clean for newer users.

My main issue:

Referencing `import { Client as TwilioChatClient } from "twilio-chat";`, the `TwilioChatClient` reconnecting logic from when `appState` switches to `foreground` from `background`.

I use Twilio Programmable Chat in many production-facing React Native projects, and this is by far the biggest issue.

package.json:
```
"twilio-chat": "3.0.0"
```
- Platform: iOS and Android, but much worse on iOS
- App is backgrounded; chat comes in as Push Notification (using a separate PN service, not Twilio)
- User taps the PN; logic is applied to navigate the User to the correct chat channel
- At this point, there's no guarantee the new message (from the PN) -- or any new Twilio messages that have been sent to this User since the last time the app was in the `foreground` -- has been handled by the `TwilioChatClient`.
- The `connectionStateChanged` listener on `TwilioChatClient` is fired, proceeds from `reconnecting` to `reconnected`, then does its business
- This ^ sometimes takes 2 seconds; other times it takes 15 seconds; other times, still, it results in a `timeout`

If you have any thoughts/advice on how to address this in React Native projects -- either in JavaScript or natively -- please let me know.

**Comment by wkoutre** [comment]
Also, on `twilio-chat@3.0.0`, I still see the `console.warn` message of:

```
YellowBox.js:82 Setting a timer for a long period of time, i.e. multiple minutes, is a performance and correctness issue on Android as it keeps the timer module awake, and timers can only be called when the app is in the foreground. See https://github.com/facebook/react-native/issues/12981 for more info.
(Saw setTimeout with duration 86400000ms)
```

I have removed all traces of `twilio-common` (previously used for AccessManager).

Without Twilio in my app: no `console.warn`
With Twilio: The above `console.warn` message is shown twice during `TwilioChatClient` setup as the app goes through its loading flow.

**Comment by zasyadev** [comment]
same issue with twilio-chat 3.0.2

**Comment by aleksandrsivanovs** [comment]
Hi!

yes, there are still long-lived setTimeouts, mostly in subscription to objects code. 
Per my understanding this is not really functionally blocking, it's warning + the timer might be off on long durations. Those are the only consequences, am I right?

**Comment by zasyadev** [comment]
Yeah, I doesn't seem to break any functionality.

**Comment by kirandash** [comment]
Has anyone found a fix for this?

Does this issue affect my App Performance? For me, the APP has become really slow after adding this chat. So, wondering if this is causing the issue.

**Comment by arthedza** [comment]
This issue lasts for two years and there are not any fixes? It doesn't break functionality but it is bad for user experience

**Comment by berkus** [comment]
I believe AccessManager has been deprecated a few years ago and since then there's no need to use it - our websocket will signal a notification when token is about to expire and needs to be refreshed.

**Comment by berkus** [comment]
For subscriptions there's nothing that can be done currently - we still need to set a 24h timeout.

**Comment by abdelmagied94** [comment]
I'm facing this issue when creating the client in android. I don't receive any response.

**Comment by berkus** [comment]
Closing.
